version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    expose:
      - 80
    # ports:
      # - 127.0.0.1:8888:80
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      bench-nw:
        ipv4_address: 192.168.100.100

  rpxy-rp:
    image: jqtype/rpxy
    container_name: proxy-rpxy
    build:
      context: ../
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - LOG_TO_FILE=false
    ports:
      - 127.0.0.1:8080:8080
    tty: false
    volumes:
      - ./rpxy.toml:/etc/rpxy.toml:ro
    networks:
      bench-nw:

  nginx-rp:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy-nginx
    ports:
      - 127.0.0.1:8090:80
    restart: unless-stopped
    tty: false
    privileged: true
    volumes:
      - ./nginx_data/vhost:/etc/nginx/vhost.d
      - ./nginx_data/conf:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      bench-nw:

  caddy-rp:
    image: caddy:2
    container_name: proxy-caddy
    ports:
      - 127.0.0.1:8100:80
    restart: unless-stopped
    tty: false
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      bench-nw:

networks:
  bench-nw:
    name: bench-nw
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
